### ISSUE TITLE
Add a Contributing Document

### ISSUE THREAD

**Issue by kjaymiller** [Python-Community-News/.github#5]
# TLDR:

Create a CONTRIBUTING.md document that contains steps for claiming an issue.

The claiming steps:

1. Enter a comment that says something to the effect of "I will work on this" and wait for a 👍🏾 from one of the organizers.
2. Fork the code in your own repo. 
3. Make the changes
4. Submit a PR

**Comment by drakeredwind01** [comment]
I will work on this.
